-- 1. 테이블 생성 (만약 없다면)
-- CREATE TABLE guestbook (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
--   name TEXT NOT NULL,
--   content TEXT NOT NULL
-- );

-- 2. RLS 활성화
ALTER TABLE guestbook ENABLE ROW LEVEL SECURITY;

-- 3. 정책 설정

-- 모든 사용자의 조회(SELECT) 허용
CREATE POLICY "Allow public select" ON guestbook
  FOR SELECT USING (true);

-- 모든 사용자의 삽입(INSERT) 허용
CREATE POLICY "Allow public insert" ON guestbook
  FOR INSERT WITH CHECK (true);

-- 수정(UPDATE) 차단 (기본적으로 policy가 없으면 차단되지만 명시적으로 확인)
-- 별도의 UPDATE policy를 만들지 않으면 차단됩니다.

-- 삭제(DELETE) 차단
-- 별도의 DELETE policy를 만들지 않으면 차단됩니다.
